# Generated by Django 5.1.7 on 2025-03-19 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='news/%Y-%m-%d/')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(max_length=500)),
                ('post', models.TextField()),
                ('published_at', models.DateTimeField()),
                ('views_count', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
